create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    auth json null,
    address character varying null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;