-- Create user table used by web3auth
create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    auth json null,
    address character varying null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

-- Create a service_role policy on public.users
CREATE POLICY service_role_access ON public.users
AS PERMISSIVE FOR ALL
TO service_role
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Create an authenticated policy on public.users
CREATE POLICY authenticated_users_can_write ON public.users
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');